import { createPublicClient, createWalletClient, http, parseAbi } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { baseSepolia } from 'viem/chains';

const PRIVATE_KEY = '0x9d75962544708d5cd5896b138ff1d8ae64e11a64e9fd3cfeb9504fb4835bea78';
const RPC_URL = 'https://base-sepolia.g.alchemy.com/v2/wfTWOqX-tfO2ahOiD3rCXzscObxKVms-';
const SETTLEMENT_ADDRESS = '0x56053B0ed4BB1b493c2B15FFa4BA21AF3d1492E4';

// Node addresses generated by the wallets
const NODE0 = '0xC67ef54A950320D1F226a225DFffD467E7991a1E';
const NODE1 = '0xE94Aed964d9579E5decf8491B3525CADD3f49919';
const NODE2 = '0x6dbE29E1bbe6b5f0CC4B324cb09e0DFC5377445e';

const SETTLEMENT_ABI = parseAbi([
  'function registerNode(address node) external',
  'function isNodeRegistered(address node) external view returns (bool)',
]);

async function main() {
  const account = privateKeyToAccount(PRIVATE_KEY);
  
  const publicClient = createPublicClient({
    chain: baseSepolia,
    transport: http(RPC_URL),
  });
  
  const walletClient = createWalletClient({
    account,
    chain: baseSepolia,
    transport: http(RPC_URL),
  });
  
  console.log('🔧 Deployer address:', account.address);
  const balance = await publicClient.getBalance({ address: account.address });
  console.log('💰 Balance:', (Number(balance) / 1e18).toFixed(4), 'ETH\n');
  
  // Register nodes
  const nodes = [
    { name: 'node0.veil', address: NODE0 },
    { name: 'node1.veil', address: NODE1 },
    { name: 'node2.veil', address: NODE2 },
  ];
  
  for (const node of nodes) {
    console.log(`📝 Registering ${node.name} (${node.address})...`);
    
    // Check if already registered
    const isRegistered = await publicClient.readContract({
      address: SETTLEMENT_ADDRESS,
      abi: SETTLEMENT_ABI,
      functionName: 'isNodeRegistered',
      args: [node.address],
    });
    
    if (isRegistered) {
      console.log(`   ✅ Already registered`);
    } else {
      const hash = await walletClient.writeContract({
        address: SETTLEMENT_ADDRESS,
        abi: SETTLEMENT_ABI,
        functionName: 'registerNode',
        args: [node.address],
      });
      
      console.log(`   ⏳ Transaction: ${hash}`);
      const receipt = await publicClient.waitForTransactionReceipt({ hash });
      console.log(`   ✅ Registered in block ${receipt.blockNumber}`);
    }
    
    // Fund node
    console.log(`💸 Funding ${node.name} with 0.005 ETH...`);
    const nodeBalance = await publicClient.getBalance({ address: node.address });
    
    if (nodeBalance > 3000000000000000n) { // > 0.003 ETH
      console.log(`   ✅ Already has ${(Number(nodeBalance) / 1e18).toFixed(4)} ETH\n`);
    } else {
      const fundHash = await walletClient.sendTransaction({
        to: node.address,
        value: 5000000000000000n, // 0.005 ETH
      });
      
      console.log(`   ⏳ Transaction: ${fundHash}`);
      const fundReceipt = await publicClient.waitForTransactionReceipt({ hash: fundHash });
      console.log(`   ✅ Funded in block ${fundReceipt.blockNumber}\n`);
    }
  }
  
  console.log('✅ All nodes registered and funded!');
}

main().catch(console.error);
